name: 16K 20-Part Parallel Test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "conversion-requests-4k20/*.txt"

jobs:
  encode:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        part: [8]
    uses: ./.github/workflows/drive-4k-segment-reusable.yml
    with:
      part: ${{ matrix.part }}
      file_id: "1PqcshMwMYAvJXhbAzY_GXOBtyqlQOvm1"
    secrets: inherit

  merge:
    needs: encode
    uses: ./.github/workflows/drive-4k-merge-reusable.yml
    secrets: inherit
